# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'pry'
  gem 'coderay'
end

group :test do
  gem 'rspec', '~> 3.9.0'
  gem 'minitest', '~> 5.12.2'
end
