# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rspec', '~> 3.7.0'
gem 'rubocop', '~> 0.51.0', require: false
